### PR TITLE
Beatify the locale files, for usability

### PR DESCRIPTION
**Pull request by FDiskas**
Beautify json. Its more easy the PageKit user to edit them localy.

### CODE REVIEW

**Comment by FDiskas** [comment]
:triangular_flag_on_post: Hope its will help somebody.

**Comment by MalteScharenberg** [comment]
Thanks for your suggestion. But why should this data been edited manually?

**Comment by FDiskas** [comment]
Not all keywords are translated. So as enduser I want to edit them manualy

**Comment by MalteScharenberg** [comment]
I not recommend to manually change system files. This makes updating very hard. Anyway these files are not directly used by Pagekit, so changing them by hand wont have any effect.

Currently we are obtaining the relative timespan CLDR from [Twitter](https://github.com/twitter/twitter-cldr-npm), who unfortunately is not offering translations for all languages. But we are thinking about a solution to provide "custom" translations (this is more complicated than just editing the files because each language has different rules to create plural forms).

**Comment by FDiskas** [comment]
That was javascript issue and was imposible to use the pagekit storage interface until i added some keywords to formats.json file

**Comment by MalteScharenberg** [comment]
Yes, but the problem was not about missing keywords but about a wrong determination of which keywords is needed (which is now fixed).

**Pull request closed without merging**
